name: Annotation
on: push
jobs:
    log:
        runs-on: ubuntu-latest
        steps:
            - run: echo "::error::error"
            - run: echo "::warning::warning"
            - run: echo "::notice::notice"
