name: Annotation
on: push
jobs:
    log:
        runs-on: ubuntu-latest
        steps:
            - run: echo "::error::error"
            - run: echo "::warning::warning"
            - run: echo "::notice::notice"
            - run: |
                echo "## Title :rocket" >> "${GITHUB_STEP_SUMMARY}"
                echo "- rfirst line" >> "${GITHUB_STEP_SUMMARY}"
                echo "- 2nd line :rocket"" >> "${GITHUB_STEP_SUMMARY}"
