name: Data Share
run-name: Data Share run-name
on: push
jobs:
    share-job:
        runs-on: ubuntu-latest
        name: share-job-name
        steps:
            - name: step1
              id: source
              run: echo "result=Hello" >> "${GITHUB_OUTPUT}"
            - env:
                RESULT: ${{ steps.source.outputs.result }}
              run: echo "${RESULT}"
            - run: echo "RESULT2=hello2" >> "${GITHUB_ENV}"
            - run: echo "${RESULT2}"
