name: Logging
on:
    push:
        paths: ['.github/workflows/logging.yml']
jobs:
    log:
        runs-on: ubuntu-latest
        env:
            SPASSWORD: SuperSecretValue
        steps:
            - run: echo "::debug::This is a debug log"
            - run: echo "This is a debug log"
            - run: |
                date
                set -x
                date
                hostname
            - run: |
                echo "::group::Show environment variables"
                printenv
                echo "::endgroup::"
            - run: echo "${SPASSWORD}"
            - run: echo "::add-mask::${SPASSWORD}"
