name: Logging
on: push
jobs:
    log:
        runs-on: ubuntu-latest
        steps:
            - run: echo "::debug::This is a debug log"
            - run: echo "This is a debug log"
            - run: |
                date
                set -x
                date
                hostname
            - run: |
                echo "::group::Show environment variables"
                printenv
                echo "::endgroup::"
