name: Parallel jobs
on:
    push:
        paths: ['.github/workflows/parallel.yml']
jobs:
    first:
        runs-on: ubuntu-latest
        steps:
            - run: sleep 10 & echo "First job"
    second:
        runs-on: ubuntu-latest
        needs: [first]
        steps:
            - run: sleep 10 & echo "Second job"
    third:
        runs-on: ubuntu-latest
        needs: [second]
        steps:
            - run: sleep 10 & echo "Third job"
