name: GO Test
on:
    push:
        paths: ['go/**/*.go']
jobs:
    test:
        runs-on: ubuntu-latest
        steps:
            - uses: actions/checkout@v4
            - uses: actions/setup-go@v5
              with:
                go-version-file: 'go/excellent/.go-version'
            - run: go test go/excellent/*.go
